const AudioActionTypes = {
    TRIG_CROWD_SOUND : 'TRIG_CROWD_SOUND',
    PLAY_ALL_CROWD_SOUNDS : 'PLAY_ALL_CROWD_SOUNDS',
    STOP_PLAYING_SOUND : 'STOP_PLAYING_SOUND',
    UPDATE_VOLUME : 'UPDATE_VOLUME',
    UPDATE_PITCH : 'UPDATE_PITCH',
}
export default AudioActionTypes