const ImageButtonsActionTypes = {
    ADD_IMAGE_BUTTON_TO_REDUX : 'ADD_IMAGE_BUTTON_TO_REDUX',
    UPDATE_IMAGE_BUTTON : 'UPDATE_IMAGE_BUTTON',
    RESET_IMAGE_BUTTON_STATES : 'RESET_IMAGE_BUTTON_STATES',
    RESET_IMAGE_BUTTON_CONTROL_STATES : 'RESET_IMAGE_BUTTON_CONTROL_STATES',
    SET_TWEAKING_IDX : 'SET_TWEAKING_IDX',
    SET_ROTATING_IDX : 'SET_ROTATING_IDX',
    SET_VOLUMING_IDX : 'SET_VOLUMING_IDX',
    SET_PITCHING_IDX : 'SET_PITCHING_IDX',

}

export default ImageButtonsActionTypes